name: Continuos Integration

on:
  push:
    branches: [main]
    paths: ["**.zig"]

  pull_request:
    branches: [main]
    paths: ["**.zig"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Run tests
        run: |
          zig env
          zig build test

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Generate code coverage report
        run: zig build cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
          env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Run lints
        run: zig build lint
