name: Continuous Integration

on:
  push:
    branches: [main]
    paths: ["**.zig"]

  pull_request:
    branches: [main]
    paths: ["**.zig"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run `test`
        run: |
          zig env
          zig build test

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Run `cov`
        run: zig build cov

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: kcov-output
          fail_ci_if_error: true
          verbose: true

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run `fmt`
        run: zig build fmt
